// <auto-generated />
using System;
using ForumData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumData.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    partial class ForumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForumDataModels.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9575c84-de6e-47db-be5e-d251390f72bd"),
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            Title = "My first post"
                        },
                        new
                        {
                            Id = new Guid("8dbfb8f3-62a7-4daa-beae-5ada9c9590d2"),
                            Content = "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            Title = "My second post"
                        },
                        new
                        {
                            Id = new Guid("fff2bd53-b4e8-4423-8377-54f80d936375"),
                            Content = "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature.",
                            Title = "My third post"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
